name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Code Linting & Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout Repo
        uses: actions/checkout@v4

      # - name: Cache Dependencies
      #   uses: actions/cache@v4
      #   id: cache
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

      - name: Install Bun
        run: bun --version || npm install -g bun

      - name: Install Dependencies
        run: bun i

      - name: Lint Code
        run: bun lint

      - name: Type Check
        run: bun ts

      - name: Format Check
        run: bun format:check
